---
- name: deploy on EC2 instance
  hosts: api
  become: yes

  tasks:
    - name: stop all containers
      docker_container:
        name: api
        state: absent

    - name: delete all images
      docker_image:
        name: ghcr.io/sa-api-test/sa-api:latest
        state: absent

    - name: login to GitHub Container Registry
      docker_login:
        registry_url: ghcr.io
        username: SergioAnastacio
        password: "{{ lookup('env', 'GITHUB_TOKEN') }}"

    - name: get docker image from github ghcr.io
      docker_image:
        name: ghcr.io/sa-api-test/sa-api:latest
        source: pull

    - name: run docker container
      docker_container:
        name: api
        image: ghcr.io/sa-api-test/sa-api:latest
        ports:
          - "80:80"
        state: started

    - name: check if container is running
      shell: docker ps
      register: result

    - debug:
        var: result.stdout