---
- name: deploy on EC2 instance
  hosts: api
  become: yes

  tasks:
    - name: stop all conteiners
      docker_container:
        name: api
        state: absent
    - name: delete all images
      docker_image:
        name: ghcr.io/sa-api-test/sa-api:2b5e308babc76c1af6f139684fc8216c910e4270
        state: absent
    - name: get docker image from github ghcr.io
      docker_image:
        name: ghcr.io/sa-api-test/sa-api:2b5e308babc76c1af6f139684fc8216c910e4270
        source: pull
    - name: run docker container
      docker_container:
        name: api
        image: ghcr.io/sa-api-test/sa-api:2b5e308babc76c1af6f139684fc8216c910e4270
        ports:
          - "80:80"
        state: started
    - name: check if container is running
      shell: docker ps
      register: result
    - debug:
        var: result.stdout
        