version: '3.8'

services:
  app:
    image: ghcr.io/sergioanastacio/sa-api-test/sa-api:latest
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
    volumes:
      - .:/var/www/html
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"