name: Deploy Infrastructure

on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform configuration
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        run: terraform apply -auto-approve

      - name: Get DB Endpoint
        id: db_endpoint
        run: echo "::set-output name=db_endpoint::$(terraform output -raw db_endpoint)"

      - name: Run Ansible Playbook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DB_HOST: ${{ steps.db_endpoint.outputs.db_endpoint }}
          DB_PORT: 3306
          DB_DATABASE: digidb
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          ansible-playbook -i inventory.ini api_deploy.yml