name: Deploy Infrastructure
on:
  workflow_dispatch:
    
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Download instance IP from S3
        run: |
          aws s3 cp s3://anastacio/inventory.ini inventory.ini
      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible
   
      - name: Decode and use private key from secrets
        run: |
             echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" | base64 --decode > private_key.pem
             chmod 600 private_key.pem
   
      - name: Verify inventory file
        run: cat inventory.ini
         
      - name: Run Ansible Playbook 
        run: |
             ansible-playbook -i inventory.ini api_deploy.yml